### ISSUE TITLE
Events from switch event provider should be reconfigurable on input method

### ISSUE THREAD

**Issue by ijdoc** [KomodoOpenLab/TeclaAccess#15]
From: https://blueprints.launchpad.net/meadl/+spec/reconfigurable-switches

The switch events from the switch event provider are currently mapped to specific actions on the input method, but in many cases it would be useful to be able to reconfigure these actions. Sample cases are:
- A user with one or two switches that are already connected to specific pins
- A sip&puff user who would like to use only soft sips/puffs to navigate the keyboard
- A user who wold like to ignore some switch events due to difficulty with targeting

**Comment by rishabhjain08** [comment]
branch : https://github.com/rishabhjain08/TeclaAccess/tree/issue15
@jorgesilva I have made some changes so that the users can re configure switch events to action mapping.
This is a test code and has not been debugged completely(as I am still trying to setup the tecla shield emulator altough I have debugged using indirect methods). Please review the changes made and tell if the progress is being made in the right direction and this is what is needed.
Some noticeable features:
1. Switch event - action mapping is only interchanged. For example. if SWITCH_J3 now maps to action A which was earlier associated with SWITH_J1 then SWITCH_J1 will automatically get associated with action B which was earlier associated with SWITH_J3. So in principle the mapping are only getting switched.
Following changes have not yet been implemented:
1. SWITCH_E1 and SWITH_E2 have their default action.(i.e. they cannot be reconfigured)
